### ISSUE TITLE
Change Request: Re-baking books button-esque feature request

### ISSUE THREAD

**Issue by lwtchu** [Connexions/cnx#47]
As a CM I would like to have a button-esque feature to re-bake a book so that I don't have to check out a book and republish it (and bumping the version up for no reason).

If there was a button, command, whatever, that'd be cool.

Acceptance criteria: I can rebake a book without having to check it out and publishing it.

**Comment by pumazi** [comment]
There is a button for this in the content-status interface (aka GOB). However, it requires authentication, which we've disabled (in cnx-publishing) for the time being, because we were working again an old version of Accounts. Perhaps the means of authentication that was recently added to Press could be implemented here, which would basically enable the button to work again.

**Comment by Bkblodget** [comment]
This will be addressed in https://app.zenhub.com/workspaces/cnx-team-5af1f4cc12da5e6d74331b60/issues/connexions/cnx/207
